### ISSUE TITLE
geolink_electaccess()

### ISSUE THREAD

**Issue by dasalm20** [SSA-Statistical-Team-Projects/GeoLink#29]
I have 3 issues: 

A): When I run the function for 2 years, it returns only one column names "elect_". I assume there is an issue in the paste0() part. 

B) :

This is the region of Nigeria that I chose: 
<img width="417" alt="Screenshot 2024-05-30 at 10 40 26 AM" src="https://github.com/SSA-Statistical-Team-Projects/GeoLink/assets/68434183/13a090de-e32a-4360-9c29-a3a1ebf7b957">

This is the same region after running the electricity function: 
<img width="344" alt="Screenshot 2024-05-30 at 10 42 14 AM" src="https://github.com/SSA-Statistical-Team-Projects/GeoLink/assets/68434183/7932dc0e-1897-4f9e-af2f-34f2790d0540">

It seems that some grids were dropped, I assumed it was because of NA values, however, when I do a summary of the gridded object I get 1684 NAs. 

If the function is not dropping NAs, why is it dropping those grids?

C) When using a shapefile the code runs, but when using a survey,  there is not default for shp_dt. Can you make sure that this function can be run using a survey?

code used: 
 test_dt <- geolink_electaccess(time_unit = "annual",
                               start_date = "2020-01-01",
                               end_date = "2022-01-01",
                               shp_dt = shp_dt[shp_dt$ADM1_EN == "Abia",])

test_dt <- geolink_electaccess(time_unit = "annual",
                               start_date = "2020-01-01",
                               end_date = "2022-01-01", 
                               survey_dt = st_as_sf(hhgeo_dt[1:50],
                                       crs = 4326), 
                               buffer_size = 1000,
                               extract_fun = "mean")

**Comment by DianaJaganjac** [comment]
Hi @dasalm20 , I have fixed the dates and survey issue you mention, I have tested it with this call and it works: df <- geolink_electaccess(start_date = "2018-12-31", end_date = "2019-12-31", shp_dt = shp_dt[shp_dt$ADM1_EN == "Lagos",])

As for the actual data we are getting, I am using lightscore and we should be getting back 0s and 1s and not NaN, I think this might have something to do with the raster being passed through zonalstats() ? @ifeanyi588

**Comment by dasalm20** [comment]
Hi @DianaJaganjac and @ifeanyi588, 

Thanks for fixing this, I am having other issues when using a  survey: 

geolink_electaccess(time_unit = "annual",
+                     start_date = "2020-01-01",
+                     end_date = "2022-01-01",
+                     survey_dt= st_as_sf(hhgeo_dt[1:50],
+                                         crs = 4326),
+                     buffer_size = 1000,
+                     extract_fun = "mean")
**Error in UseMethod("st_bbox") : 
  no applicable method for 'st_bbox' applied to an object of class "NULL"**

**Comment by dasalm20** [comment]
Dear @DianaJaganjac  and @ifeanyi588 , 

Everything above is sorted out. The main issue now is the following:

1- Regardless of what year you input, you will get back a column for each year from 2012-2019. 

2- We are only getting lightscore, I am not sure if there is demand for the other indicators. But if there is, please add it to teh function. @ifeanyi588  should be able to tells us if we only need lightscore or the others too. 



This is the sample code I used: 

**test_dt <- geolink_electaccess(start_date = "2020-01-01",
                                                    end_date = "2021-01-01",
                                                    shp_dt = shp_dt[shp_dt$ADM1_EN == "Abia",])**

**Comment by dasalm20** [comment]
Dear @ifeanyi588 - @DianaJaganjac , 

Did anybody worked on this function ?

Best, 
Daylan

**Comment by dasalm20** [comment]
Dear @DianaJaganjac, 

The electricity function is still not working well. Could you please take a look? 

code:
 test_dt <- geolink_electaccess(start_date = "2018-01-01",
                                               end_date = "2019-02-01",
                                               shp_dt = shp_dt[shp_dt$ADM1_PCODE == "NG001",],
                                               grid_size = 1000,
                                               extract_fun = "mean")


Error :

Error in compute_zonalstats(shp_dt = shp_dt, raster_objs = raster_objs,  : 
  Length of name_set must match number of raster objects
In addition: Warning messages:
1: attribute variables are assumed to be spatially constant throughout all geometries 
2: In st_collection_extract.sf(add_dt) :
  x contains no geometries of specified type
